In [2]:
import numpy as np
import pandas as pd


In [3]:
# two matrics
array1 = np.array([[5, 9, 3],[3, 7, 5]])
array2 = np.array([[3,-9],[5, 4],[7, -8]])
print(array1)
print(array2)

[[5 9 3]
 [3 7 5]]
[[ 3 -9]
 [ 5  4]
 [ 7 -8]]


In [4]:
array = np.random.rand(3, 4)
print(array)


[[0.58326637 0.69656726 0.71845812 0.98152401]
 [0.39614391 0.71845739 0.07414525 0.2880736 ]
 [0.45822842 0.78060501 0.28720041 0.79419702]]


In [5]:
mul = np.dot(array1, array2)
print(mul)

[[ 81 -33]
 [ 79 -39]]


In [6]:
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[81, -33], [79, -39]]


In [7]:
mean = np.mean(array1)
print(mean)

5.333333333333333
